rabbitmq:
  server:
    host: "127.0.0.1"
    port: 5672
    queue: "bungeeBansMQ"
  spawn1:
    host: "127.0.0.1"
    port: 5672
    queue: "spawnBansMQ"
  north:
    host: "127.0.0.1"
    port: 5672
    queue: "spawnBansMQ"
